# Generated by Django 4.2.27 on 2026-01-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL friendly name (auto-generated)', unique=True)),
                ('category', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=255)),
                ('excerpt', models.TextField(help_text='Short summary for home page')),
                ('content', models.TextField(help_text='Full article content')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_url', models.CharField(help_text='URL to icon image (e.g., https://cdn...) or Material Icon name', max_length=255)),
                ('is_image', models.BooleanField(default=True, help_text='Check if using an image URL, Uncheck if using Material Icon text')),
            ],
        ),
        migrations.CreateModel(
            name='TechTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='features',
            field=models.TextField(help_text='Comma-separated list'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_name',
            field=models.CharField(max_length=50),
        ),
    ]
