# Generated by Django 4.2.27 on 2026-01-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogpost_marketingfeature_techtool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.CharField(help_text='URL to client logo image', max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('IN_HOUSE', 'In-House Project'), ('ONGOING', 'Ongoing Project'), ('COMPLETED', 'Completed Case Study')], default='ONGOING', max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
