# Generated by Django 4.2.27 on 2026-01-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Innovative Digital Solutions', max_length=50)),
                ('heading_line_1', models.CharField(default='Scale Your Vision', max_length=50)),
                ('heading_gradient_text', models.CharField(default='Globally.', max_length=50)),
                ('subtext', models.TextField(default='From custom software to viral marketing strategies, we provide the engine for your growth.')),
            ],
            options={
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
