# Generated by Django 4.2.27 on 2026-01-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Innovative Digital Solutions', max_length=50)),
                ('heading_line_1', models.CharField(default='Scale Your Vision', max_length=50)),
                ('heading_gradient_text', models.CharField(default='Globally.', max_length=50)),
                ('subtext', models.TextField(default='From custom software to viral marketing strategies...')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order of appearance (1, 2, 3...)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
