# Generated by Django 4.2.27 on 2026-01-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_heroslide_delete_herosection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='long_description',
            field=models.TextField(default='', help_text='Shown on the detailed Service page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(default='', help_text='Shown on Home Page cards'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL friendly name (auto-generated)', unique=True),
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='check_circle', help_text='Material Icon name', max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='main.service')),
            ],
        ),
    ]
